openapi: 3.0.0
info:
    title: Vertex Monitoring
    description: A monitoring service for Vertex.
    version: 0.0.0
servers:
    - url: http://{ip}:{port-kernel}/api
      variables:
        ip:
            default: localhost
            description: The IP address of the server.
        port-kernel:
            default: "7506"
            description: The port of the server.
paths:
    /collector/{collector}/install:
        post:
            operationId: vx_monitoring_install_collector
            summary: Install a collector
            tags:
                - Monitoring
            parameters:
                - in: query
                  name: collector
                  description: The collector to install.
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    $ref: '#/components/responses/200'
                "400":
                    $ref: '#/components/responses/400'
                "404":
                    $ref: '#/components/responses/404'
                "500":
                    $ref: '#/components/responses/500'
    /metrics:
        get:
            operationId: vx_monitoring_get_metrics
            summary: Get metrics
            tags:
                - Monitoring
            responses:
                "200":
                    description: The metrics.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Metrics'
    /visualizer/{visualizer}/install:
        post:
            operationId: vx_monitoring_install_visualizer
            summary: Install a visualizer
            tags:
                - Monitoring
            parameters:
                - in: query
                  name: visualizer
                  description: The visualizer to install.
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    $ref: '#/components/responses/200'
                "400":
                    $ref: '#/components/responses/400'
                "404":
                    $ref: '#/components/responses/404'
                "500":
                    $ref: '#/components/responses/500'
components:
    responses:
        "200":
            description: Success
        "201":
            description: Created
        "204":
            description: No content
        "304":
            description: Not modified
        "400":
            description: Bad request
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "401":
            description: Unauthorized
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "404":
            description: Resource not found
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "409":
            description: Conflict
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "422":
            description: Unprocessable entity
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "500":
            description: Internal error
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
    schemas:
        ErrCode:
            type: string
        Error:
            type: object
            properties:
                code:
                    $ref: '#/components/schemas/ErrCode'
                message:
                    type: string
        Metrics:
            type: string
