openapi: 3.0.1
info:
    title: Vertex Admin
    description: Administer Vertex
    version: ""
paths:
    /api/admin/checks:
        get:
            tags:
                - Checks
            summary: Get all checks
            description: Check that all vertex requirements are met.
            operationId: check
            responses:
                "200":
                    description: OK
    /api/ping:
        get:
            summary: Ping the app
            operationId: ping
            responses:
                "204":
                    description: No Content
    /api/settings:
        get:
            tags:
                - Settings
            summary: Get settings
            operationId: getSettings
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TypesAdminSettings'
        patch:
            tags:
                - Settings
            summary: Patch settings
            operationId: patchSettings
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PatchSettingsInput'
            responses:
                "200":
                    description: OK
    /api/update:
        get:
            tags:
                - Update
            summary: Get the latest update information
            operationId: getUpdate
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TypesUpdate'
components:
    schemas:
        BaselineBaseline:
            type: object
            properties:
                date:
                    type: string
                description:
                    type: string
                version:
                    type: string
                vertex:
                    type: string
                vertex_client:
                    type: string
                vertex_services:
                    type: string
        PatchSettingsInput:
            type: object
            properties:
                settings:
                    $ref: '#/components/schemas/TypesAdminSettings'
        TypesAdminSettings:
            type: object
            properties:
                created_at:
                    type: integer
                    format: int64
                deleted_at:
                    type: integer
                    format: int64
                    nullable: true
                id:
                    type: integer
                    format: int32
                updated_at:
                    type: integer
                    format: int64
                updates_channel:
                    type: string
                webhook:
                    type: string
                    nullable: true
        TypesUpdate:
            type: object
            properties:
                baseline:
                    $ref: '#/components/schemas/BaselineBaseline'
tags:
    - name: Checks
    - name: Settings
    - name: Update
