openapi: 3.0.1
info:
    title: Vertex SQL
    description: Create and manage SQL databases.
    version: ""
paths:
    /api/about:
        get:
            summary: Get server info
            operationId: getAbout
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CommonAbout'
    /api/container/{container_uuid}:
        get:
            tags:
                - Container
            summary: Get an installed DBMS
            operationId: getDBMS
            parameters:
                - name: container_uuid
                  in: path
                  required: true
                  schema:
                    type: string
                    format: uuid
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TypesDBMS'
    /api/dbms/{dbms}/install:
        post:
            tags:
                - DBMS
            summary: Install a DBMS
            operationId: installDBMS
            parameters:
                - name: dbms
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TypesContainer'
    /api/ping:
        get:
            summary: Ping the app
            operationId: ping
            responses:
                "204":
                    description: No Content
components:
    schemas:
        CommonAbout:
            type: object
            properties:
                arch:
                    type: string
                    example: amd64
                commit:
                    type: string
                    example: cd4ba2876f45775287f426c13adb1868f7c96222
                date:
                    type: string
                    example: 2006-01-02T15:04:05Z07:00
                os:
                    type: string
                    example: linux
                version:
                    type: string
                    example: 1.2.3
        TypesContainer:
            type: object
            properties:
                color:
                    type: string
                    example: '#336699'
                    nullable: true
                command:
                    type: string
                    example: tunnel run
                    nullable: true
                databases:
                    type: object
                    additionalProperties:
                        type: array
                        items:
                            type: integer
                            format: int32
                        maxItems: 16
                        minItems: 16
                description:
                    type: string
                    example: An SQL database.
                    nullable: true
                icon:
                    type: string
                    example: simpleicons/postgres.svg
                    nullable: true
                id:
                    type: string
                    format: uuid
                image:
                    type: string
                    example: postgres
                image_tag:
                    type: string
                    example: latest
                launch_on_startup:
                    type: boolean
                    example: true
                name:
                    type: string
                    example: Postgres
                status:
                    type: string
                    example: running
                template_id:
                    type: string
                    example: postgres
                update:
                    $ref: '#/components/schemas/TypesContainerUpdate'
                user_id:
                    type: string
                    format: uuid
        TypesContainerUpdate:
            type: object
            properties:
                current_version:
                    type: string
                latest_version:
                    type: string
        TypesDB:
            type: object
            properties:
                name:
                    type: string
        TypesDBMS:
            type: object
            properties:
                databases:
                    type: array
                    items:
                        $ref: '#/components/schemas/TypesDB'
                password:
                    type: string
                username:
                    type: string
tags:
    - name: Container
    - name: DBMS
