openapi: 3.0.0
info:
    title: Vertex Reverse Proxy
    description: A reverse proxy manager.
    version: 0.0.0
servers:
    - url: http://{ip}:{port-kernel}/api
      variables:
        ip:
            default: localhost
            description: The IP address of the server.
        port-kernel:
            default: "7508"
            description: The port of the server.
paths:
    /redirect:
        post:
            operationId: vx_reverse_proxy_add_redirect
            summary: Add redirect
            tags:
                - Reverse Proxy
            requestBody:
                description: The redirect to add.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRedirectBody'
            responses:
                "204":
                    $ref: '#/components/responses/204'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
    /redirect/{id}:
        delete:
            operationId: vx_reverse_proxy_remove_redirect
            summary: Remove redirect
            tags:
                - Reverse Proxy
            parameters:
                - in: query
                  name: id
                  description: The redirect UUID.
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    $ref: '#/components/responses/204'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
    /redirects:
        get:
            operationId: vx_reverse_proxy_get_redirects
            summary: Get redirects
            tags:
                - Reverse Proxy
            responses:
                "200":
                    description: The redirects.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Redirect'
components:
    responses:
        "200":
            description: Success
        "201":
            description: Created
        "204":
            description: No content
        "304":
            description: Not modified
        "400":
            description: Bad request
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "401":
            description: Unauthorized
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "404":
            description: Resource not found
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "409":
            description: Conflict
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "422":
            description: Unprocessable entity
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "500":
            description: Internal error
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
    schemas:
        AddRedirectBody:
            type: object
            properties:
                source:
                    type: string
                target:
                    type: string
        ErrCode:
            type: string
        Error:
            type: object
            properties:
                code:
                    $ref: '#/components/schemas/ErrCode'
                message:
                    type: string
        Redirect:
            type: string
