openapi: 3.0.1
info:
    title: Vertex Tunnels
    description: Create and manage tunnels.
    version: ""
paths:
    /api/ping:
        get:
            summary: Ping the app
            operationId: func1
            responses:
                "200":
                    description: OK
    /api/provider/{provider}/install:
        post:
            summary: Install a tunnel provider
            operationId: installProvider
            parameters:
                - name: provider
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
components: {}
