openapi: 3.0.1
info:
    title: Vertex Reverse Proxy
    description: Redirect traffic to your containers.
    version: ""
paths:
    /api/about:
        get:
            summary: Get server info
            operationId: getAbout
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CommonAbout'
    /api/ping:
        get:
            summary: Ping the app
            operationId: ping
            responses:
                "204":
                    description: No Content
    /api/redirect:
        post:
            tags:
                - Redirect
            summary: Add redirect
            operationId: addRedirect
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRedirectInput'
            responses:
                "200":
                    description: OK
    /api/redirect/{id}:
        delete:
            tags:
                - Redirect
            summary: Remove redirect
            operationId: removeRedirect
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    format: uuid
            responses:
                "200":
                    description: OK
    /api/redirects:
        get:
            tags:
                - Redirects
            summary: Get redirects
            operationId: getRedirects
            responses:
                "200":
                    description: OK
components:
    schemas:
        AddRedirectInput:
            type: object
            properties:
                source:
                    type: string
                target:
                    type: string
            required:
                - source
                - target
        CommonAbout:
            type: object
            properties:
                arch:
                    type: string
                    example: amd64
                commit:
                    type: string
                    example: cd4ba2876f45775287f426c13adb1868f7c96222
                date:
                    type: string
                    example: 2006-01-02T15:04:05Z07:00
                os:
                    type: string
                    example: linux
                version:
                    type: string
                    example: 1.2.3
tags:
    - name: Redirect
    - name: Redirects
