openapi: 3.0.0
info:
    title: Vertex Admin
    description: Retrieve the logged-in user credentials
    version: 0.0.0
servers:
    - url: http://{ip}:{port-kernel}/api
      variables:
        ip:
            default: localhost
            description: The IP address of the server.
        port-kernel:
            default: "7500"
            description: The port of the server.
paths:
    /admin/checks:
        get:
            operationId: admin_checks
            summary: Get all checks
            tags:
                - Checks
            description: Check that all vertex requirements are met.
            responses:
                "200":
                    $ref: '#/components/responses/200'
    /app/admin/hardware/cpus:
        get:
            operationId: get_cpus
            summary: Get CPUs
            tags:
                - Hardware
            responses:
                "200":
                    description: The CPUs information.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/CPU'
                "500":
                    $ref: '#/components/responses/500'
    /app/admin/hardware/host:
        get:
            operationId: get_host
            summary: Get host
            tags:
                - Hardware
            responses:
                "200":
                    description: The host information.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Host'
                "500":
                    $ref: '#/components/responses/500'
    /app/admin/hardware/reboot:
        post:
            operationId: reboot
            summary: Reboot
            tags:
                - Hardware
            responses:
                "204":
                    $ref: '#/components/responses/204'
                "500":
                    $ref: '#/components/responses/500'
    /app/admin/settings:
        get:
            operationId: get_settings
            summary: Get settings
            tags:
                - Settings
            responses:
                "200":
                    description: The settings.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Settings'
                "500":
                    $ref: '#/components/responses/500'
        patch:
            operationId: patch_settings
            summary: Patch settings
            tags:
                - Settings
            requestBody:
                description: The settings to update.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Settings'
            responses:
                "200":
                    $ref: '#/components/responses/200'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
    /app/admin/ssh:
        delete:
            operationId: delete_ssh_key
            summary: Delete SSH key
            tags:
                - SSH
            parameters:
                - in: query
                  name: fingerprint
                  description: The fingerprint of the SSH key to delete.
                  required: true
                  schema:
                    $ref: '#/components/schemas/DeleteSSHKeyBody'
            responses:
                "204":
                    $ref: '#/components/responses/204'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
        get:
            operationId: get_ssh_keys
            summary: Get all SSH keys
            tags:
                - SSH
            responses:
                "200":
                    description: The list of SSH keys.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/PublicKey'
                "500":
                    $ref: '#/components/responses/500'
        post:
            operationId: add_ssh_key
            summary: Add an SSH key
            tags:
                - SSH
            requestBody:
                description: The SSH key to add.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddSSHKeyBody'
            responses:
                "201":
                    $ref: '#/components/responses/201'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
    /app/admin/ssh/users:
        get:
            operationId: get_ssh_users
            summary: Get all users that can have SSH keys
            tags:
                - SSH
            responses:
                "200":
                    description: The list of users.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/User'
                "500":
                    $ref: '#/components/responses/500'
    /app/admin/update:
        get:
            operationId: get_updates
            summary: Get the latest version info
            tags:
                - Updates
            responses:
                "200":
                    description: The latest version information.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Update'
                "500":
                    $ref: '#/components/responses/500'
        post:
            operationId: install_update
            summary: Install the latest version
            tags:
                - Updates
            responses:
                "204":
                    $ref: '#/components/responses/204'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
components:
    responses:
        "200":
            description: Success
        "201":
            description: Created
        "204":
            description: No content
        "304":
            description: Not modified
        "400":
            description: Bad request
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "401":
            description: Unauthorized
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "404":
            description: Resource not found
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "409":
            description: Conflict
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "422":
            description: Unprocessable entity
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "500":
            description: Internal error
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
    schemas:
        AddSSHKeyBody:
            type: object
            properties:
                authorized_key:
                    type: string
                username:
                    type: string
        Baseline:
            type: object
            properties:
                date:
                    type: string
                description:
                    type: string
                version:
                    type: string
                vertex:
                    type: string
                vertex_client:
                    type: string
                vertex_services:
                    type: string
        CPU:
            type: object
            properties:
                cache_size:
                    type: int32
                core_id:
                    type: string
                cores_count:
                    type: int32
                count:
                    type: int32
                family:
                    type: string
                flags:
                    type: array
                    items:
                        type: string
                mhz:
                    type: float64
                microcode:
                    type: string
                model:
                    type: string
                model_name:
                    type: string
                physical_id:
                    type: string
                stepping:
                    type: int32
                vendor_id:
                    type: string
        DeleteSSHKeyBody:
            type: object
            properties:
                fingerprint:
                    type: string
                username:
                    type: string
        ErrCode:
            type: string
        Error:
            type: object
            properties:
                code:
                    $ref: '#/components/schemas/ErrCode'
                message:
                    type: string
        Host:
            type: object
            properties:
                boot_time:
                    type: uint64
                host_id:
                    type: string
                hostname:
                    type: string
                kernel_arch:
                    type: string
                kernel_version:
                    type: string
                os:
                    type: string
                platform:
                    type: string
                platform_family:
                    type: string
                platform_version:
                    type: string
                procs:
                    type: uint64
                uptime:
                    type: uint64
                virtualization_role:
                    type: string
                virtualization_system:
                    type: string
        PublicKey:
            type: object
            properties:
                fingerprint_sha_256:
                    type: string
                type:
                    type: string
                username:
                    type: string
        Settings:
            type: string
        Update:
            type: object
            properties:
                baseline:
                    $ref: '#/components/schemas/Baseline'
                updating:
                    type: boolean
        User:
            type: object
