openapi: 3.0.0
info:
    title: Vertex Auth
    description: Retrieve the logged-in user credentials
    version: 0.0.0
servers:
    - url: http://{ip}:{port-kernel}/api
      variables:
        ip:
            default: localhost
            description: The IP address of the server.
        port-kernel:
            default: "7502"
            description: The port of the server.
paths:
    /app/auth/credentials:
        get:
            operationId: auth_get_current_user_credentials
            summary: Get user credentials
            tags:
                - Users
            responses:
                "200":
                    description: The user credentials
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserCredentials'
                "500":
                    $ref: '#/components/responses/500'
    /app/auth/login:
        post:
            operationId: auth_login
            summary: Login
            tags:
                - Auth
            responses:
                "200":
                    description: The auth token
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Token'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
    /app/auth/logout:
        post:
            operationId: auth_logout
            summary: Logout
            tags:
                - Auth
            responses:
                "204":
                    $ref: '#/components/responses/204'
                "500":
                    $ref: '#/components/responses/500'
    /app/auth/register:
        post:
            responses: {}
    /app/auth/user:
        get:
            operationId: auth_get_current_user
            summary: Get user
            tags:
                - Users
            responses:
                "200":
                    description: The user
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                "500":
                    $ref: '#/components/responses/500'
        patch:
            operationId: auth_patch_current_user
            summary: Patch user
            tags:
                - Users
            responses:
                "200":
                    description: The user
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                "500":
                    $ref: '#/components/responses/500'
    /app/auth/user/email:
        delete:
            operationId: auth_current_user_delete_email
            summary: Delete email
            tags:
                - Emails
            responses:
                "204":
                    $ref: '#/components/responses/204'
                "500":
                    $ref: '#/components/responses/500'
        post:
            operationId: auth_current_user_create_email
            summary: Create email
            tags:
                - Emails
            responses:
                "200":
                    description: The email
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Email'
                "400":
                    $ref: '#/components/responses/400'
                "409":
                    description: Email already exists
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    $ref: '#/components/responses/500'
    /app/auth/user/emails:
        get:
            operationId: auth_current_user_get_emails
            summary: Get emails
            tags:
                - Emails
            responses:
                "200":
                    description: The emails
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Email'
                "500":
                    $ref: '#/components/responses/500'
    /app/auth/verify:
        post:
            operationId: auth_verify
            summary: Verify
            tags:
                - Authentication
            responses:
                "200":
                    description: The auth token
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Token'
                "400":
                    $ref: '#/components/responses/400'
                "500":
                    $ref: '#/components/responses/500'
components:
    responses:
        "200":
            description: Success
        "201":
            description: Created
        "204":
            description: No content
        "304":
            description: Not modified
        "400":
            description: Bad request
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "401":
            description: Unauthorized
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "404":
            description: Resource not found
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "409":
            description: Conflict
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "422":
            description: Unprocessable entity
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
        "500":
            description: Internal error
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
    schemas:
        Email:
            type: object
            properties:
                created_at:
                    type: int64
                deleted_at:
                    type: int64
                email:
                    type: string
                id:
                    type: uint
                updated_at:
                    type: int64
                user_id:
                    type: uint
        ErrCode:
            type: string
        Error:
            type: object
            properties:
                code:
                    $ref: '#/components/schemas/ErrCode'
                message:
                    type: string
        Token:
            type: string
        User:
            type: object
        UserCredentials:
            type: string
