openapi: 3.0.1
info:
    title: Vertex Reverse Proxy
    description: Redirect traffic to your containers.
    version: ""
paths:
    /api/ping:
        get:
            summary: Ping the app
            operationId: ping
            responses:
                "204":
                    description: No Content
    /api/redirect:
        post:
            tags:
                - Redirect
            summary: Add redirect
            operationId: addRedirect
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRedirectInput'
            responses:
                "200":
                    description: OK
    /api/redirect/{id}:
        delete:
            tags:
                - Redirect
            summary: Remove redirect
            operationId: removeRedirect
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    $ref: '#/components/schemas/UuidNullUUID'
            responses:
                "200":
                    description: OK
    /api/redirects:
        get:
            tags:
                - Redirects
            summary: Get redirects
            operationId: getRedirects
            responses:
                "200":
                    description: OK
components:
    schemas:
        AddRedirectInput:
            type: object
            properties:
                source:
                    type: string
                target:
                    type: string
            required:
                - source
                - target
        UuidNullUUID:
            type: object
            properties:
                UUID:
                    type: string
                    format: uuid
                Valid:
                    type: boolean
tags:
    - name: Redirect
    - name: Redirects
