openapi: 3.0.1
info:
    title: Vertex Reverse Proxy
    description: Redirect traffic to your containers.
    version: ""
paths:
    /api/ping:
        get:
            summary: Ping the app
            operationId: func1
            responses:
                "200":
                    description: OK
    /api/redirect:
        post:
            summary: Add redirect
            operationId: addRedirect
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRedirectInput'
            responses:
                "200":
                    description: OK
    /api/redirect/{id}:
        delete:
            summary: Remove redirect
            operationId: removeRedirect
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    $ref: '#/components/schemas/UuidNullUUID'
            responses:
                "200":
                    description: OK
    /api/redirects:
        get:
            summary: Get redirects
            operationId: getRedirects
            responses:
                "200":
                    description: OK
components:
    schemas:
        AddRedirectInput:
            type: object
            properties:
                source:
                    type: string
                target:
                    type: string
            required:
                - source
                - target
        UuidNullUUID:
            type: object
            properties:
                UUID:
                    type: array
                    items:
                        type: integer
                        format: int32
                    maxItems: 16
                    minItems: 16
                Valid:
                    type: boolean
