openapi: 3.0.1
info:
    title: Vertex Tunnels
    description: Create and manage tunnels.
    version: ""
paths:
    /api/about:
        get:
            summary: Get server info
            operationId: getAbout
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CommonAbout'
    /api/ping:
        get:
            summary: Ping the app
            operationId: ping
            responses:
                "204":
                    description: No Content
    /api/provider/{provider}/install:
        post:
            tags:
                - Provider
            summary: Install a tunnel provider
            operationId: installProvider
            parameters:
                - name: provider
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
components:
    schemas:
        CommonAbout:
            type: object
            properties:
                arch:
                    type: string
                    example: amd64
                commit:
                    type: string
                    example: cd4ba2876f45775287f426c13adb1868f7c96222
                date:
                    type: string
                    example: 2006-01-02T15:04:05Z07:00
                os:
                    type: string
                    example: linux
                version:
                    type: string
                    example: 1.2.3
tags:
    - name: Provider
