openapi: 3.0.1
info:
    title: Vertex Monitoring
    description: Create and manage containers.
    version: ""
paths:
    /api/collector/{collector}:
        get:
            tags:
                - Collector
            summary: Get a collector
            operationId: getCollector
            parameters:
                - name: collector
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TypesCollector'
    /api/collector/{collector}/install:
        post:
            tags:
                - Collector
            summary: Install a collector
            operationId: installCollector
            parameters:
                - name: collector
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
    /api/ping:
        get:
            summary: Ping the app
            operationId: ping
            responses:
                "200":
                    description: OK
    /api/visualizer/{visualizer}/install:
        post:
            tags:
                - Visualizer
            summary: Install a visualizer
            operationId: installVisualizer
            parameters:
                - name: visualizer
                  in: path
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    description: OK
components:
    schemas:
        MetricMetric:
            type: object
            properties:
                description:
                    type: string
                id:
                    type: string
                labels:
                    type: array
                    items:
                        type: string
                name:
                    type: string
                type:
                    type: string
        TypesCollector:
            type: object
            properties:
                is_alive:
                    type: boolean
                metrics:
                    type: array
                    items:
                        $ref: '#/components/schemas/MetricMetric'
tags:
    - name: Collector
    - name: Visualizer
